name: Build ipk for HomeProxy

on:
  push:
    branches:
      - 'master'
      - 'dev'
    tags:
      - 'v*'
    paths:
      - 'htdocs/**'
      - 'po/**'
      - 'root/**'
      - 'Makefile'
      - '.github/**'

  pull_request:
    branches:
      - 'master'
      - 'dev'
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'htdocs/**'
      - 'root/**'
      - 'Makefile'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4

      - name: Build ipk file
        env:
          RELEASE_TYPE: ${{ github.event_name }}
        run: |
          pushd .github
          fakeroot bash build-ipk.sh
          echo "ASSET_NAME=$(ls *.ipk)" >> $GITHUB_ENV
          popd

      - name: Publishing to GitHub Artifacts
        uses: actions/upload-artifact@v4
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: ${{ env.ASSET_NAME }}
          path: .github/*.ipk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: .github/*.ipk
          generate_release_notes: true
